openapi: 3.0.1
title: Delilha Resto
description: Primer sprint proyect de ACAMICA
contact:
  name: Ignacio Spahr
  email: ignaspahr@gmail.com
license:
  name: MIT
servers:
  - url: http://localhost:9090/api/v1
    description: develompment server
paths:
  /usuarios:
    put:
      description: Inicia sesión
      tags:
      - Usuario
      requestBody:
        description: Email y contraseña para iniciar sesion
        content:
          application/json:
            required: true
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Sesion iniciada con exito
        406:
          description: Usuario no registrado
    post:
      description: Crear cuenta
      tags:
      - Usuario
      requestBody:
        content:
          application/json:
            description: Datos para crear la nueva cuenta
            required: true
            schema:
              type: object
              properties:
                userName:
                  type: string
                name:
                  type: string
                email:
                  type: string
                phoneNumber:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Usuario creado con exito
        406:
          description: El nombre de usuario y/o email ya se ecuentra registrado
        416:
          description: Debe completar todos los campos
  /usuarios/direcciones:
    post:
      security:
        - bearerAuth: []
      description: Agregar direccion
      tags:
      - Usuario/direcciones
      requestBody:
        description: Direccion que se quiere agregar
        content:
          application/json:
            required: true
            schema:
              type: object
              properties:
                direccion:
                  type: string
      responses:
        200:
          description: Direccion agregada
        401:
          description: Usted no esta autorizado
        403:
          description: Usted es un usuario administrador. No puede realizar esta accion
    get:
      security:
        - bearerAuth: []
      description: Muestra las direcciones del usuario
      tags:
      - Usuario/direcciones
      responses:
        200:
          description: Lista de direcciones
        401:
          description: Usted no esta autorizado.
        403:
          descripction: El usuario esta suspendido y no puede acceder.
  /usuarios/admin:
    put:
      security:
        - bearerAuth: []
      description: Administrador suspende a un usuario
      tags:
      - Usuario/admin
      requestBody:
        description: Id del usuario que se quiere suspender
        content:
          application/json:
            required: true
            schema:
              type: object
              properties:
                userId:
                  type: integer
      responses:
        200:
          description: Direccion agregada
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
  /productos:
    post:
      security:
        - bearerAuth: []
      description: Crea un nuevo producto
      tags:
      - Productos
      parameters:
      - name: nombre
        in: header
        description: El nombre del nuevo producto
        required: true
        type: string
      - name: precio
        in: header
        description: El precio del nuevo producto
        required: true
        type: integer
      responses:
        200:
          description: Producto agregado correctamente
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
        406:
          description: Producto ya registrado o formato de parametros no válido
    put:
      security:
        - bearerAuth: []
      description: Edita un producto existente por su ID
      tags:
      - Productos
      requestBody:
        description: A JSON object containing pet information
        content:
          application/json:
            description: datos para crear el nuevo producto
            required: true
            schema:
              type: object
              properties:
                platoID:
                  type: integer
                plato:
                  type: string
                precio:
                  type: integer
      responses:
        200:
          description: Producto editado correctamente
        400:
          description: "Obligatorio: {platoID: Number} Opcional(al menos uno): {precio:Number} o {plato:string}"
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
        404:
          descripction: platoID no encontrado
    delete:
      security:
        - bearerAuth: []
      description: Elimina un producto existente por su ID
      tags:
      - Productos
      requestBody:
        description: ID del producto que se desea borrar
        content:
          application/json:
            required: true
            schema:
              type: object
              properties:
                platoID:
                  type: integer
      responses:
        200:
          description: Producto eliminado correctamente
        400:
          description: platoID debe ser un numero
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
        404:
          descripction: platoID no encontrado
    get:
      security:
        - bearerAuth: []
      description: Ver todos los productos
      tags:
      - Productos
      responses:
        200:
          description: Producto eliminado correctamente
        401:
          description: Usted no esta autorizado.
        403:
          descripction: El usuario esta suspendido y no puede acceder.
  /pedidos:
    post:
      security:
        - bearerAuth: []
      description: Un usuario realiza un nuevo pedido
      tags:
      - Pedidos
      requestBody:
        description: Listado de los productos que quiere comprar
        content:
          application/json:
            required: true
            schema:
              type: object
              properties:
                mediosPagoId:
                  type: integer
                direccioneId:
                  type: integer
                listaProductos:
                  type: array
                  items:
                    type: object
                    properties:
                      ProductoId:
                        type: integer
                      cantidad:
                        type: integer
      responses:
        200:
          description: Pedido agregado con exito
        400:
          description: Body no es valido o platoid no valido
        403:
          description: El usuario esta suspendido y no puede acceder
    get:
        security:
          - bearerAuth: []
        description: Muestra los pedidos de un usuario
        tags:
        - Pedidos
        responses:
          200:
            description: Productos mostrados correctamente
          404:
            description: El usuario no tiene pedidos
          403:
            description: El usuario esta suspendido y no puede acceder
    put:
      security:
        - bearerAuth: []
      description: Un usuario edita un pedido existente
      tags:
      - Pedidos
      parameters:
      - name: pedidoid
        in: header
        description: ID del pedido que se desea modificar
        required: true
        type: integer
      requestBody:
        description: Listado de los productos que desea editar
        content:
          application/json:
            required: true
            schema:
              type: object
              properties:
                listaProductos:
                  type: array
                  items:
                    type: object
                    properties:
                      ProductoId:
                        type: integer
                      cantidad:
                        type: integer
      responses:
        200:
          description: Pedido actualizado
        403:
          description: El usuario esta suspendido y no puede acceder
        406:
          description: Error, no se pudo completar la respuesta
    delete:
      security:
        - bearerAuth: []
      description: Un usuario elimina productos de un pedido
      tags:
      - Pedidos
      parameters:
      - name: pedidoid
        in: header
        description: ID del pedido que se desea elimiar
        required: true
        type: integer
      requestBody:
        description: Listado de los prodcutos que desea eliminar
        content:
          application/json:
            required: true
            schema:
              type: object
              properties:
                listaProductos:
                  type: array
                  items:
                    type: object
                    properties:
                      productoId:
                        type: integer
      responses:
          200:
            description: Productos eliminados
          400:
            description:  Error, no se pudo completar la respuesta
          403:
            description: El usuario esta suspendido y no puede acceder
  /pedidos/admin:
    get:
      security:
        - bearerAuth: []
      description: Un administrador puede ver todos los pedidos
      tags:
      - Pedidos Admin
      responses:
        200:
          description: Se muestran los pedidos
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
    put:
      security:
        - bearerAuth: []
      description: Un administrador modifica el estado de un pedido
      tags:
      - Pedidos Admin
      parameters:
      - name: pedidoid
        in: header
        description: ID del pedido que se desea modificar el estado
        required: true
        type: integer
      - name: nuevo_estado
        in: header
        description: El nuevo estado que sera asignado al pedido
        required: true
        type: string
      responses:
        200:
          description: Estado del pedido cambiado a confirmado
        400:
          description: platoID no encontrado
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
  /pedidos/confirmado:
    put:
      security:
        - bearerAuth: []
      description: Un usuario cambia el estado de su pedido a confirmado
      tags:
        - Pedidos Confirmado
      responses:
        200:
          description: Estado cambiado a confirmado
        406:
          description: Un error y no se pudo hacer la modificacion
  /medios-de-pago:
    post:
      security:
        - bearerAuth: []
      description: Agrega medio de pago
      tags:
      - Medios de Pago
      parameters:
      - name: nuevo
        in: header
        description: Nombre del nuevo medio de pago
        required: true
        type: string
      responses:
        200:
          description: Pedido agregado con exito
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
    get:
      security:
        - bearerAuth: []
      description: Muestra todos los medios de pago
      tags:
      - Medios de Pago
      responses:
        200:
          description: Medios de pago correctamente
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
    put:
      security:
        - bearerAuth: []
      description: Actualiza un medio de pago
      tags:
      - Medios de Pago
      parameters:
      - name: nuevo_nombre
        in: header
        description: Nuevo nombre del nuevo medio de pago
        required: true
        type: string
      - name: medio_id
        in: header
        description: ID del medio de pago a modificar
        required: true
        type: integer
      responses:
        200:
          description: Medio de pago editado correctamente
        406:
          description: El medio de pago ID no existe
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
    delete:
      security:
        - bearerAuth: []
      description: Elimina un medio de pago
      tags:
      - Medios de Pago
      parameters:
      - name: medio_id
        in: header
        description: ID del medio de pago a eliminar
        required: true
        type: integer
      responses:
        200:
          description: Medio de pago eliminado correctamente
        406:
          description: El medio de pago ID no existe
        401:
          description: Usted no esta autorizado
        403:
          description: No puede realizar esta accion
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
